#!/bin/bash

# Abyei Deployment Script
# Deploys frontend to Vercel and backend to Railway

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🚀 Abyei Students in Rwanda - Deployment Script        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Installing..."
    npm install -g vercel
fi

# Check git status
echo "📋 Checking git status..."
if [[ -z $(git status -s) ]]; then
    echo "✅ Working directory clean"
else
    echo "⚠️  You have uncommitted changes. Commit them first:"
    echo "   git add . && git commit -m 'Your message'"
    exit 1
fi

# Prompt for deployment choice
echo ""
echo "Select deployment target:"
echo "1) Deploy frontend only (Vercel)"
echo "2) Deploy backend only (Railway)"
echo "3) Deploy both frontend and backend"
echo "4) Configure environment variables only"
read -p "Enter choice (1-4): " choice

case $choice in
    1)
        echo ""
        echo "🚀 Deploying frontend to Vercel..."
        cd apps/frontend
        vercel --prod
        cd ../..
        echo "✅ Frontend deployment complete!"
        echo "Visit your Vercel dashboard: https://vercel.com/dashboard"
        ;;
    2)
        echo ""
        echo "🚀 Backend deployment guide:"
        echo "1. Go to https://railway.app"
        echo "2. Sign in with GitHub"
        echo "3. Create new project → Deploy from GitHub"
        echo "4. Select repository: kanukiir-afk/abyei"
        echo "5. Set root directory: apps/backend"
        echo "6. Configure variables in Railway dashboard"
        echo ""
        read -p "Press Enter after deploying backend to Railway..."
        ;;
    3)
        echo ""
        echo "🚀 Starting full deployment..."
        echo ""
        echo "Step 1: Frontend (Vercel)"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━"
        cd apps/frontend
        vercel --prod
        FRONTEND_URL=$(vercel ls 2>/dev/null | grep -o 'https://[^ ]*' | head -1)
        cd ../..
        echo "✅ Frontend deployed!"
        if [ -n "$FRONTEND_URL" ]; then
            echo "📍 Frontend URL: $FRONTEND_URL"
        fi
        echo ""
        echo "Step 2: Backend (Railway)"
        echo "━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Now deploy backend:"
        echo "1. Go to https://railway.app"
        echo "2. Create new project → Deploy from GitHub"
        echo "3. Select: kanukiir-afk/abyei"
        echo "4. Root directory: apps/backend"
        read -p "Press Enter after backend deployment..."
        read -p "Enter your Railway backend URL (e.g., https://abyei-backend.railway.app): " backend_url
        
        if [ -n "$backend_url" ]; then
            echo ""
            echo "Step 3: Update Environment Variables"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "✅ Update NEXT_PUBLIC_API_URL in Vercel with: $backend_url"
            echo "  Then redeploy frontend"
        fi
        ;;
    4)
        echo ""
        echo "📝 Environment Variables Setup"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Vercel Environment Variables:"
        echo "  - NEXT_PUBLIC_API_URL = [your-railway-backend-url]"
        echo ""
        echo "Railway Environment Variables:"
        echo "  - DATABASE_URL = [auto-generated by Railway]"
        echo "  - JWT_SECRET = [change in production]"
        echo "  - NODE_ENV = production"
        echo "  - PORT = 4000"
        echo ""
        echo "Go to:"
        echo "  📍 Vercel: https://vercel.com/dashboard"
        echo "  📍 Railway: https://railway.app/dashboard"
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   ✅ Deployment process complete!                         ║"
echo "║   📖 See DEPLOY_QUICK_START.md for full instructions     ║"
echo "╚════════════════════════════════════════════════════════════╝"
